let posts = [
  {
    timeframe: "after 7 to close",
    title: "20% off apples",
    description: "get 20% off any fuji apples",
    company: "H-Mart",
    location: "los angeles",
    sold_out: false,
    distance: 4.7,
  },
  {
    timeframe: "from open to noon",
    title: "Beef 30% off",
    description: "30% off marked beef and beef products",
    company: "H-Mart",
    location: "los angeles",
    location: "los angeles",
    sold_out: false,
    distance: 5.6,
  },
  {
    timeframe: "after 7 to close",
    title: "50% off bread",
    description: "get 50% off any fresh made daily bread",
    company: "Walmart los angeles",
    location: "los angeles",
    location: "los angeles",
    sold_out: false,
    distance: 2.6,
  },
  {
    timeframe: "from open to noon",
    title: "Deli items 75 off",
    description: "75% off any hot and ready deli items",
    company: "Walmart los angeles",
    location: "los angeles",
    location: "los angeles",
    sold_out: false,
    distance: 20.7,
  },
  {
    timeframe: "after 7 to close",
    title: "10% off pastries",
    description: "get 10% off any made fresh daily pastries",
    company: "starbucks",
    location: "los angeles",
    location: "los angeles",
    sold_out: false,
    distance: 18.9,
  },
  {
    timeframe: "11-noon",
    title: "70% off breakfast items",
    description: "70% off made breakfast items",
    company: "starbucks",
    location: "los angeles",
    location: "los angeles",
    sold_out: false,
    distance: 20.1,
  },
  {
    timeframe: "all day today",
    title: "50% off potatoes",
    description: "get 50% off marked potatoes",
    company: "Trader Joes",
    location: "los angeles",
    location: "los angeles",
    sold_out: false,
    distance: 17.3,
  },
  {
    timeframe: "Thurday",
    title: "bananas 10% off",
    description: "10% off made  ripe bananas",
    company: "Trader Joes",
    location: "los angeles",
    location: "los angeles",
    sold_out: false,
    distance: 27.8,
  },
  {
    timeframe: "all day today",
    title: "40% off seafood",
    description: "get 40% off marked seafood all day",
    company: "costco",
    location: "los angeles",
    location: "los angeles",
    sold_out: false,
    distance: 26.7,
  },
  {
    timeframe: "Saturday",
    title: "chicken 75% off",
    description: "75% off marked chicken",
    company: "costco",
    location: "los angeles",
    location: "los angeles",
    sold_out: false,
    distance: 24.8,
  },
  {
    timeframe: "5pm - close",
    title: "40% off organic fruits",
    description: "get 40% off marked organic foods",
    company: "whole foods",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 3.1,
  },
  {
    timeframe: "Friday",
    title: "milk 30% off",
    description: "30% off milk and milk products",
    company: "whole foods",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 6.3,
  },
  {
    timeframe: "12-1pm",
    title: "50% off annual flowers",
    description: "get 50% off all annual flowers",
    company: "sams club",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 6.5,
  },
  {
    timeframe: "Monday",
    title: "bread 25% off",
    description: "25% off made expiring bread",
    company: "sams club",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 2.3,
  },
  {
    timeframe: "Monday",
    title: "bread 10% off",
    description: "30% off made expiring bread",
    company: "Walmart anaheim",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 7.8,
  },
  {
    timeframe: "Thurday",
    title: "bananas 20% off",
    description: "20% off made over ripe bananas",
    company: "Walmart anaheim",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 10.2,
  },
  {
    timeframe: "Monday",
    title: "Herbs 40% off",
    description: "40% off select Herbs",
    company: "target",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 8.9,
  },
  {
    timeframe: "friday from 8 - 10pm",
    title: "dairy products 20% off",
    description: "20% off select dairy products",
    company: "target",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 12.7,
  },
  {
    timeframe: "Monday",
    title: "bananas 70% off",
    description: "70% off old bananas",
    company: "George's Grocery Store",
    location: "portland",
    location: "los angeles",
    sold_out: false,
    distance: 5.8,
  },
  {
    timeframe: "last week of spring",
    title: "seeds 50% off",
    description: "50% off spring seeds",
    company: "Joja Mart",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 3.2,
  },
  {
    timeframe: "all summer",
    title: "75% off seeds",
    description: "75% off spring seeds",
    company: "Joja Mart",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 2.9,
  },
  {
    timeframe: "8am-9am",
    title: "Early Bird Special: 30% off",
    description: "30 off all fruit and produce",
    company: "Pierre's General Store,",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 0.4,
  },
  {
    timeframe: "10pm-close",
    title: "20% off expiring farming supply",
    description: "20% off all expiring farming supply",
    company: "Pierre's General Store,",
    location: "anaheim",
    location: "los angeles",
    sold_out: false,
    distance: 1.3,
  },
];
